#!/usr/bin/env bash

#when you return from learning about bash/shell data structures and algorithms, learning how it stores values and passes references, etc.,you plan to implement the following: 
#use the below jan-dec global variables in a function that all init funcs can use, and further add to this function a way for it to be stored in an array that the other init funcs can use without them interfeering with eachother, each having their own state to whatever extent possible, also in this function write a long switch statement with global variables for the possible date %m%Y%b%d...etc., so that the innitFuncs can use their own local variables to interface with the global variables array.
mkdirPath="/bin/mkdir"
datePath="/bin/date"
thisYear="$($datePath -j +%Y)"


jan="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
feb="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
mar="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
apr="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
may="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
jun="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
jul="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
aug="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
sep="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
oct="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
nov="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName
dec="$($datePath -j -f %m%Y $month$day$Year +%m%b)"_$calenderName

getAllMonthsArray() {

for monthIndex in {01..12}
   do
	allMonths="$($datePath -j -f %m%Y $monthIndex$thisYear +%m%b)"_$calenderName
	return_allMonthsArray+=($allMonths)
   done
 
}

initAllMonthsFunc() {

for monthIndex in {01..12}
   do
	allMonths="$($datePath -j -f %m%Y $monthIndex$thisYear +%m%b)"_$calenderName
	return_allMonthsArray+=($allMonths)

	if   [[ "$mkdirMonths" == "true" ]]; then 
		$mkdirPath -p $initYearPath/$allMonths && echo "$allMonths directory has successfully been created in $thisYear.$calenderName." 
	elif [[ "$mkdirMonths" == "false" ]]; then 
		echo "warning: allMonths directories have not been created, mkdirMonths variable is set to $mkdirMonths." && break 
	elif [[ -n "$mkdirMonths" ]]; then 
		echo "mkdirMonths:$mkdirMonths is mis-spelled or it does  not exist, it needs to be either true or false." && $(rm -R $initYearPath) && break	
	else  
		: 		
	fi
   done
}

initYear() {

local currentYearPath="$(pwd)/$thisYear"
initYearPath=$currentYearPath"_$calenderName"
$mkdirPath $initYearPath 

}


initMonths() {
#local mkdirMonths="false"
local mkdirMonths="true"

initAllMonthsFunc; 
}

initWeeks() {

local thisYear="$($datePath -j +%Y)"
local allWeeksArray=()
#local allMonthsArray=($globalMonths)
#
#local jan=${allMonthsArray[0]}
#local feb=${allMonthsArray[1]}
#local mar=${allMonthsArray[2]}
#local apr=${allMonthsArray[3]}
#local may=${allMonthsArray[4]}
#local jun=${allMonthsArray[5]}
#local jul=${allMonthsArray[6]}
#local aug=${allMonthsArray[7]}
#local sep=${allMonthsArray[8]}
#local oct=${allMonthsArray[9]}
#local nov=${allMonthsArray[10]}
#local dec=${allMonthsArray[11]}
#
local thisYear="$($datePath -j +%Y)"
#globalGetAllMonths


#for weekIndex in {01..366..07}
#  do 
#    local allWeeks="$($datePath -j -f %j%Y $weekIndex$thisYear +%b_%A%d_week%V)"_$calenderName
#
#    allWeeksArray+=($allWeeks)
#    #$mkDir -p $decPath/{$allWeeksOfDec},}
#  done
echo ${allMonthsArray[@]}
#echo $jan
 }

read -p "Enter the name of your calender: " calenderName
initYear
initMonths
#initWeeks
#initDays

#mkdir -p head/{shoulders/{hand,feet},}



